# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml', '0002_auto_20160627_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='af',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='results',
            name='freq',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
